boolean-uk/team-dev-server

- .env.example
- prisma/migrations/20220408104349_add_post_model/migration.sql
- prisma/schema.prisma
- src/controllers/auth.js
- src/controllers/post.js
- src/domain/user.js
- src/index.js
- src/middleware/auth.js
- src/routes/post.js
- src/utils/config.js
- src/utils/responses.js
> Create posts (hardcoded)

- src/controllers/post.js
- src/index.js
- src/middleware/auth.js
- src/routes/post.js
> Get all posts

- src/controllers/user.js
- src/routes/user.js
- src/utils/responses.js
> Get user route

- src/controllers/user.js
- src/domain/user.js
- src/index.js
- src/routes/user.js
> Get all users route

- src/controllers/cohort.js
- src/domain/cohort.js
- src/index.js
- src/middleware/auth.js
- src/routes/cohort.js
- src/utils/responses.js
> add cohort create route

- src/controllers/user.js
- src/routes/user.js
> add user to cohort (hardcoded)

- prisma/schema.prisma
- Created PostComment model.
- updated the Schema with the following one to many linked to PostComment.
> Prisma Schema updated (PostComment) - B

- src/controllers/user.js
- src/domain/user.js
Changing some variables to camel case caused issues with object destructuring as the properties from json didnt match
.
to fix this i assigned the variables individually.
> correcting variables

- src/controllers/post.js
Issue: https://github.com/boolean-uk/team-dev-server/projects/1#card-81246255
Modified controller function to include 'profile' so that client-side can access first and last name data.
> profile added to getAll controller

- prisma/migrations/20220427154926_postcomment/migration.sql
- src/controllers/post.js
- src/routes/post.js
Create a new endpoint and a controller function to create new comments on post
> Updated create comment

- .env.example
- src/controllers/user.js
- src/domain/user.js
- src/routes/user.js
Created feature to update the logged user details. This was initially implemented as a `PATCH` request but it has been changed to a `PUT` request for simplicity. Validation has also been implemented and tested with ThunderClient
> 35 updating user data validation

- src/controllers/user.js
- src/domain/user.js
- src/routes/user.js
Implemented the server response and database update for conneting a user with a cohort.
> 53 update user implement prisma

- src/controllers/user.js
- src/domain/user.js
- src/routes/user.js
Added **error handling**  to the **getStudentWithoutCohort** function.
> 57 students in specific cohort

- src/controllers/posts/likes.js
- src/controllers/posts/post.js
Implemented: https://github.com/boolean-uk/team-dev-server/issues/73
> 73 controller updates for like functionality

- README.md
- task a
- task b
https://github.com/boolean-uk/team-dev-server/issues/81
> Add name Edward to Readme

- README.md
Reverts boolean-uk/team-dev-server#92
> Revert "Add name Edward to Readme"

- README.md
- prisma/migrations/20220628162644_cohort_name_unique_added_to_cohort_model/migration.sql
- prisma/schema.prisma
- src/controllers/cohort.js
- src/domain/cohort.js
https://github.com/boolean-uk/team-dev-server/issues/119
> Cohorts now can have a name.

- src/controllers/user.js
Task completed: Token added to response in create function user.js
User can automatically login after user registers #124
> User can automatically login after user registers

- src/domain/post.js
team user profile can now add profile urls to the comments and post
> ps-133-user-object-to-comment-and-post

- prisma/migrations/20220707135446_submission_table/migration.sql
- prisma/schema.prisma
> Create Submission Table in Schema

- src/controllers/deliveryLog.js
- src/domain/deliveryLog.js
- src/routes/deliveryLog.js
We can GET all delivery logs and GET delivery log by id.
https://github.com/boolean-uk/team-dev-server/issues/174
> can GET all delivery logs and GET delivery log by id

- prisma/migrations/20220707135446_submission_table/migration.sql
> Up 158 create submission schema

- prisma/schema.prisma
> CohortExercise and Submission prisma tables

- src/domain/exercise.js
re: [https://github.com/boolean-uk/team-dev-server/issues/196](url)
> Change to Json method on exercise name

- src/controllers/note.js
- src/controllers/user.js
- src/routes/cohort.js
- src/routes/user.js
issue #193 
We have realized that methods related to notes were in multiple files.
In order to make it easier to understand, we have extracted methods related to notes and relocated them into controller/note.js.
> extracted methods from user.js to note.js

- prisma/schema.prisma
- src/controllers/user.js
- src/domain/Submission.js
- src/routes/user.js
--> created endpoint for creating Submission
--> added a little update to Schema - "UpdatedAt"
--> tested with Insomnia
> created endpoint for create Submission

- src/controllers/cohort.js
- src/routes/cohort.js
re: https://github.com/boolean-uk/team-dev-client/issues/227
> Navigation to profile bug fixed

- src/domain/user.js
Temporary feature which will be paired with a radio button or checkbox on the client side to create a teacher account. If the checkbox is checked on the client side, a teacher role will be added to the request body.
> #209 tta - add role parameter to create teacher

- src/controllers/post.js
Modified the getAll function to send back a response to the client.
> Tp #211 server return data from db

- prisma/migrations/20220913161950_add_created_at_updated_at_to_post_model/migration.sql
- prisma/schema.prisma
- src/controllers/post.js
Here I fixed the create post function and introduced elements of jwt extraction and communication with the database.
> Tp #31 add create post function in api

- src/controllers/post.js
Managed to have the right info of user and profile displayed, with the ascending order.
> hotfix-getAll_working_properly

- src/controllers/post.js
Used 'asc' instead of 'desc'. Chenged it now to give the right response to Client.
> fix: sorting by time fixed

- package-lock.json
- src/controllers/user.js
- src/domain/user.js
- src/routes/user.js
Added updateUserById function in user controller and /user/:id put route in user routes. A frontend put request to this route can now update the users profile information.
> feat: add update user by id put request to /user/:id route

- src/controllers/post.js
- src/routes/post.js
> feat: add edit function to "/post/:id" route

- prisma/migrations/20220915110944_add_created_at_updated_at_to_post_model/migration.sql
- prisma/schema.prisma
> hotfix: updatedAt given nullable attribute

- prisma/schema.prisma
- src/controllers/user.js
update: updateUserById now updates the users password or doesn't change it if no new password provided
Schema also updated, users password now has a 250 max char limit.
> update: updateUserById now updates the users password

- prisma/seed.js
Updated seed file with more students and more posts
> Tp #41 update seed file

- src/middleware/auth.js
validateAuthentication will now return an error if the token has expired.
> add: tokenExpiryCheck to validateAuthentication

- prisma/migrations/20220927130354_comment_replies/migration.sql
- prisma/schema.prisma
- prisma/seed.js
- src/controllers/post.js
- Added self relation to Comment model to allow comment replies
- Updated createComment controller to accept `parentId`
- Cleaned up redundant try catch
- Added comment replies in the seed
> Tp #263 comment replies

- prisma/migrations/20220927111542_add_admin_role/migration.sql
- prisma/schema.prisma
- prisma/seed.js
- src/controllers/admin.js
- src/controllers/user.js
- src/index.js
- src/middleware/auth.js
- src/routes/admin.js
#60 As product owner, to protect my application from sinister actors, I want to remove the role toggle on register
> Tta #60 add admin role

- prisma/migrations/20220928163334_change_profile_visibility_column_to_post_privacy_pref/migration.sql
- prisma/schema.prisma
- src/controllers/user.js
- src/domain/user.js
Altered/updated the visibility column in Profile table to postPrivacyPref to relate more to the data it's holding.
> fix: change visibility column to postPrivacyPref & change type to string in domain
